config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL a vailable within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :restaurants

  resources :restaurants, only: [:show, :update] do
    resources :categories, only: [:index]
    resource :dashboard, only: [:show, :overview]
    get "/overview", to: "dashboards#overview"
  end

  # resources :dashboard, only: [:show], as: :dashboard
  root to: 'dashboards#show'

  resources :categories, only: [:create, :destroy] do
    resources :items, only: [:index, :new, :create, :edit, :update]
  end

  resources :items, only: :destroy do
    resources :session_items, only: [:create]
  end

  resources :session_items, only: [:index, :destroy] do
    collection do
      get "status", as: :status
    end
  end

  resources :tables, only: [] do
    resources :sessions, only: [:new, :update]
  end

  resources :sessions, only: [] do
    collection do
      get "closed", as: :closed
    end
    member do
      patch :session_items, to: "session_items#update"
    end
  end

  # resources :categories, only: [:create, :destroy] do
  #   resources :items, only: [:new, :create, :edit, :update]
  # end
  # get '/dashboard', to: 'dashboards#show', as: :dashboard
  # resources :restaurants, only: :update
  # resources :items, only: :destroy
end

app/models/session_item.rb
class SessionItem < ApplicationRecord
  belongs_to :session
  belongs_to :item
end

app/controllers/session_items_controller.rb
class SessionItemsController < ApplicationController
  skip_before_action :authenticate_restaurant!

  def index
    @session_items = @current_session.session_items
    @restaurant = @current_session.restaurant

    @ordered_items = @current_session.session_items.where(sent_to_kitchen: true).group_by{ |session_item| session_item.item_id }
    @unordered_items = @current_session.session_items.where(sent_to_kitchen: false).group_by{ |session_item| session_item.item_id }
  end

  def create
    @item = Item.find(params[:item_id])
    @session_item = SessionItem.create(session: @current_session, item: @item, quantity: 1)
    if @session_item.save
      respond_to do |format|
        format.html {
          redirect_back(fallback_location: session_items_path)
         }
        format.text {
          render(
            partial: 'shared/item_card',
            locals: { item: @session_item.item, item_quantity: @current_session.session_items.where(sent_to_kitchen: false, item_id: @item.id).count },
            formats: [:html]
          )
        }
      end
    end
  end

  def update
    # find the session_items within my order
    @current_session.session_items
    # update the sent_to_kitchen boolean to true for all the items
    @current_session.session_items.each do |session_item|
      session_item.update(sent_to_kitchen: true)
    end
    redirect_to status_session_items_path
  end

  def destroy
    @session_item = SessionItem.find(params[:id])

    # all of this is here because we have to refactor the partial
    @category = @session_item.item.category
    @session_items_per_item = @current_session.session_items.group(:item_id).count
    # all of this is here because we have to refactor the partial

    if @session_item.destroy
      render(
        partial: 'shared/item_card',
        locals: { item: @session_item.item, item_quantity: @current_session.session_items.where(sent_to_kitchen: false, item_id: @session_item.item_id).count },
        formats: [:html]
      )
    end
  end

  def status
  end
end

app/views/session_items/index.html.erb
<%= render "shared/visitor-navbar" %>
<div class="yellowbackground">

  <div class="top-card-checkout">
    <div class="backtocat">
      <%= link_to restaurant_categories_path(@restaurant) do%>
        <i class="far fa-arrow-alt-circle-left arrow-left-order"></i>
      <% end %>
    </div>
  </div>

  <div class="checkout-card">
    <strong><h1>My Order</h1></strong>
    <p>Bill total: <%= number_to_currency(@current_session.bill_total, locale: :es) %></p>
  </div>

  <% @unordered_items.each do |item_id, session_items| %>
    <% item = Item.find(item_id) %>
    <%= render "shared/item_card", item: item, item_quantity: session_items.count %>
  <% end %>

  <% @ordered_items.each do |item_id, session_items| %>
    <% item = Item.find(item_id) %>
    <div class="item-card card-grey">
      <div class="item-img">
          <%= cl_image_tag item.photo.key %>
      </div>
      <div class="item-info">
        <p><%= item.name %></p>
        <div class="price-quantity">
          <strong><%= number_to_currency(item.price * session_items.count, locale: :es) %></strong>
          <div class="quant-buttons">
            <div id="quantity" class="card-grey">Already Ordered:  <%= session_items.count || 0 %></div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="blank-card"></div>
<div class="w-100 fixed-bottom mb-4 text-center">
  <%= link_to(session_items_session_path(@current_session), method: :patch, class:"order-link") do %>
    <button class="order-button" data-controller="order-total"
            data-action="updated-order@window->order-total#priceUpdate">
            Send Order | <span data-order-total-target="price">
            <%= number_to_currency(@current_session.order_total, locale: :es) %></span>
    </button>
  <% end %>
</div>

app/views/session_items/status.html.erb
<body class = backgroundyellow>
  <%= image_tag "eyeqtablewhite.png", class:"logowhite center" %>
  <h4 class = statusdesign>
    Your order will be with you shortly!
  </h4>
  <div class="w-100 fixed-bottom mb-4">
    <%= link_to restaurant_path(@current_session.restaurant) do %>
      <button class="menu-button" id="back-to-home">Back to home</button>
    <% end %>
  </div>
</body>