config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL a vailable within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :restaurants

  resources :restaurants, only: [:show, :update] do
    resources :categories, only: [:index]
    resource :dashboard, only: [:show, :overview]
    get "/overview", to: "dashboards#overview"
  end

  # resources :dashboard, only: [:show], as: :dashboard
  root to: 'dashboards#show'

  resources :categories, only: [:create, :destroy] do
    resources :items, only: [:index, :new, :create, :edit, :update]
  end

  resources :items, only: :destroy do
    resources :session_items, only: [:create]
  end

  resources :session_items, only: [:index, :destroy] do
    collection do
      get "status", as: :status
    end
  end

  resources :tables, only: [] do
    resources :sessions, only: [:new, :update]
  end

  resources :sessions, only: [] do
    collection do
      get "closed", as: :closed
    end
    member do
      patch :session_items, to: "session_items#update"
    end
  end

  # resources :categories, only: [:create, :destroy] do
  #   resources :items, only: [:new, :create, :edit, :update]
  # end
  # get '/dashboard', to: 'dashboards#show', as: :dashboard
  # resources :restaurants, only: :update
  # resources :items, only: :destroy
end

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active highlightsize">
          <img class="d-block w-100" src="https://res.cloudinary.com/dwonn5etb/image/upload/v1638519867/eyeqtable/patatas-bravas_f42yuj.png" alt="Patatas Bravas">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 " src="https://res.cloudinary.com/dwonn5etb/image/upload/v1637924925/eyeqtable/calamari_swprhr.png" alt="Calamari">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://res.cloudinary.com/dwonn5etb/image/upload/v1637922471/eyeqtable/Tapas_hu4ryk.png" alt="Ham & Cheese">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" id="croquetas" src="https://res.cloudinary.com/dwonn5etb/image/upload/v1637924918/eyeqtable/croqueta_xuzs1a.png" alt="Croquetas">
        </div>
        <div class="carousel-item">
          <img class="d-block w-10" id="chorizo" src="https://res.cloudinary.com/dwonn5etb/image/upload/v1637924919/eyeqtable/chorizo_yjqyzs.png" alt="Chorizo">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-google"></i></i></a>
  </div>
  <div class="footer-copyright">
    Carrer de Joaquim Ruyra, 9, 11 08025 Barcelona, Spain <i class="fas fa-heart"></i> in association with Le Wagon
  </div>
</div>

app/views/shared/_item-show-modal.html.erb
<div class="modal fade bd-example-modal-sm" id="item-show-<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="item-card">
        <div class = "item-card-images"><%= cl_image_tag item.photo.key %></div>
        <div class="item-info">
          <p><%= item.name %></p>
          <%= item.description %>
          <div class="price-quantity">
            <strong><%= number_to_currency(item.price, locale: :es) %></strong>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_item_card.html.erb
<div data-controller="item-quantity" data-url="<%= item_session_items_path(item) %>"  >
    <div class="item-card item-card-link" data-toggle='modal' data-target="#item-show-<%= item.id %>" >
      <%= cl_image_tag item.photo.key %>
      <div class="item-info">
        <p><%= item.name %></p>
        <div class="price-quantity">
          <strong data-item-quantity-target="price"><%= number_to_currency(item.price, locale: :es) %></strong>
          <div class="quant-buttons">
            <% if @current_session.session_items.where(item: item).any? %>
              <%= button_to session_item_path(item.session_items.last), method: :delete, remote: true, data: { action: "click->item-quantity#deleteSessionItem", "delete-url":  session_item_path(item.session_items.last) } do %>
                <%= image_tag "minus.svg" %>
              <% end %>
            <% else %>
              <%= button_to "", disabled: true do %>
                <%= image_tag "minus.svg" %>
              <% end %>
            <% end %>
            <div class="quantity" data-item-quantity-target="quantity">
              <%= item_quantity %>
            </div>
            <%= button_to item_session_items_path(item), remote: true, data: { action: "click->item-quantity#createSessionItem" } do %>
              <%= image_tag "plus.svg" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <%= render "shared/item-show-modal", item: item %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light">
  <ul>
    <li class="nav-item">
      <%= link_to restaurant_path(@current_session.restaurant) do %>
        <%= image_tag "logo.svg", class:"avatar" %>
      <% end %>
    </li>
    <li class="nav-item">
      <h6><%= image_tag "table.svg", class:"avatar" %> - No°<%= @current_session.table.number %></h6>
    </li>
    <li class="nav-item">
      <%= link_to session_items_path do %>
        <%= image_tag "order.svg", class:"avatar" %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_restaurant-navbar.html.erb
<nav class="navbar-side">
  <div class="nav-content">
    <%= link_to restaurant_dashboard_path(current_restaurant) do %>
      <%= image_tag "logo.svg", class:"navbar-logo-dashboard" %>
    <% end %>
    <%= link_to restaurant_overview_path(current_restaurant), class:"overview-button" do %>
      <%= image_tag "dinner-table.png", class:"navbar-logo-dashboard" %>
    <% end %>
    <div class="notifications">
      <%= image_tag "bell.png", class:"navbar-logo-dashboard" %>
    </div>
  </div>
</nav>

app/views/shared/_visitor-navbar.html.erb
<nav class="navbar navbar-light">
  <ul>
    <li class="nav-item">
      <%= link_to restaurant_path(@current_session.restaurant) do %>
        <%= image_tag "logo.svg", class:"avatar" %>
      <% end %>
    </li>
    <li id="table-nav-item">
      <h6><%= image_tag "table.svg", id:"avatar-center" %> - No°<%= @current_session.table.number %></h6>
    </li>
    <li class="nav-item">
      <%= link_to session_items_path do %>
        <%= image_tag "order.svg", class:"avatar" %>
      <% end %>
    </li>
  </ul>
</nav>