config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL a vailable within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :restaurants

  resources :restaurants, only: [:show, :update] do
    resources :categories, only: [:index]
    resource :dashboard, only: [:show, :overview]
    get "/overview", to: "dashboards#overview"
  end

  # resources :dashboard, only: [:show], as: :dashboard
  root to: 'dashboards#show'

  resources :categories, only: [:create, :destroy] do
    resources :items, only: [:index, :new, :create, :edit, :update]
  end

  resources :items, only: :destroy do
    resources :session_items, only: [:create]
  end

  resources :session_items, only: [:index, :destroy] do
    collection do
      get "status", as: :status
    end
  end

  resources :tables, only: [] do
    resources :sessions, only: [:new, :update]
  end

  resources :sessions, only: [] do
    collection do
      get "closed", as: :closed
    end
    member do
      patch :session_items, to: "session_items#update"
    end
  end

  # resources :categories, only: [:create, :destroy] do
  #   resources :items, only: [:new, :create, :edit, :update]
  # end
  # get '/dashboard', to: 'dashboards#show', as: :dashboard
  # resources :restaurants, only: :update
  # resources :items, only: :destroy
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @categories = current_restaurant.categories
  end

  def overview
    # all open session_items.where(sent_to_kitchen: true)
    @sessions = current_restaurant.sessions.where(done: false)
    @session = Session.last
  end
end

app/views/dashboards/_edit-form.html.erb
<div class="form-group update-restaurant-background" data-controller="hide-form">
  <button data-action="click->hide-form#toggleForm" class = "restaurant-details">Update Restaurant Details
    <i class="fas fa-angle-down text-align-right" style = "text-align: right"></i>
  </button>
  <div class = "formcontent">
    <%= simple_form_for current_restaurant, html: { class: 'd-none', data: { hide_form_target: 'form' } } do |f| %>
      <%= f.input :name %>
      <%= f.input :cuisine %>
      <%= f.input :instagram_url %>
      <%= f.input :facebook_url %>
      <%= f.input :tripadvisor_url %>
      <%= f.input :logo, as: :file  %>
      <div class = "btn btn-update-restaurant"><%= f.button :submit %></div>
    <% end %>
    </div>
</div>

app/views/dashboards/overview.html.erb
<div class="dashboard-overview-container">
  <%= render "shared/restaurant-navbar" %>
  <div class = "overview-body">
    <h1>Table Orders</h1>
    <div class="table-overview-plan">
      <%= image_tag "tableplan.png" %>
    </div>
  </div>
  <div class="active-orders-column">
    <div class="active-orders-card">
      <h2>Order #<%= @session.id %></h2>
      <p>Table number: <%= @session.table.number %></p>
      <p> <%= @session.updated_at.strftime('%D -%r') %> </p>
      <ul class="list-unstyled">
        <% @session.distinct_items.each do |item| %>
          <% items_count = @session.items_count %>
          <li>
            <% quantity = items_count[item.name] %>
            <p><%= quantity %>x <%= item.name %> </p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%# comment by Sasha: we have a little problem here with the display of quantity.. work in progress %>

app/views/dashboards/show.html.erb
<div class="dashboard-show-container">
  <%= render "shared/restaurant-navbar" %>
  <div class="inner-show-container">
    <div class="edit-form">
      <%= render "edit-form" %>
    </div>
    <h3>Menu Categories</h3>
    <% @categories.each do |category| %>
        <div class="dash-category-card">
          <h3><%= category.name %></h3>
          <div class="dash-item-list">
              <% category.items.each do |item| %>
                <div class="dash-card">
                  <div class="dashboard-img"><%= cl_image_tag item.photo.key %></div>
                  <div class="d-flex item-name-price">
                    <div><strong><%= item.name %></strong></div>
                    <div><strong><%= number_to_currency(item.price, locale: :es) %></strong></div>
                  </div>
                  <div class ="item-description-format"><%= item.description %></div>
                  <ul class = "item-buttons">
                    <li class = "d-flex justify-content-lg-center">
                      <%= link_to edit_category_item_path(category, item) do %>
                        <button type= "button" class = "btn btn-change-item"><i class="fas fa-edit"></i></button>
                      <% end %>
                      <%= link_to item_path(item), method: :delete, data: { confirm: "Are you sure you want to delete?" } do %>
                        <button type= "button" class = "btn btn-del-item"><i class="fas fa-times"></i></button>
                      <% end %>
                    </li>
                  </ul>
                </div>
              <% end %>
          </div>
          <div class="dash-cat-buttons">
            <%= link_to new_category_item_path(category) do %>
              <button type="button" class="btn btn-info"><i class="fas fa-plus"></i> Add Item</button>
            <% end %>
            <%= link_to category_path(category), method: :delete, data: { confirm: "Are you sure you want to delete?" } do %>
              <button type="button" class="btn btn-warning"><i class="fas fa-times"></i> Delete Category</button>
            <% end %>
          </div>
        </div>
    <% end %>
    <div class="add-category" data-controller="hide-form">
      <button data-action="click->hide-form#toggleForm" class = "btn btn-add-item">Add New Category
        <i class="fas fa-angle-down text-align-right" style = "text-align: right"></i>
      </button>
      <%= simple_form_for Category.new, html: { class: 'd-none', data: { hide_form_target: 'form' } } do |f| %>
        <div>
          <div><%= f.input :name %></div>
          <div><%= f.button :submit %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>