config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL a vailable within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :restaurants

  resources :restaurants, only: [:show, :update] do
    resources :categories, only: [:index]
    resource :dashboard, only: [:show, :overview]
    get "/overview", to: "dashboards#overview"
  end

  # resources :dashboard, only: [:show], as: :dashboard
  root to: 'dashboards#show'

  resources :categories, only: [:create, :destroy] do
    resources :items, only: [:index, :new, :create, :edit, :update]
  end

  resources :items, only: :destroy do
    resources :session_items, only: [:create]
  end

  resources :session_items, only: [:index, :destroy] do
    collection do
      get "status", as: :status
    end
  end

  resources :tables, only: [] do
    resources :sessions, only: [:new, :update]
  end

  resources :sessions, only: [] do
    collection do
      get "closed", as: :closed
    end
    member do
      patch :session_items, to: "session_items#update"
    end
  end

  # resources :categories, only: [:create, :destroy] do
  #   resources :items, only: [:new, :create, :edit, :update]
  # end
  # get '/dashboard', to: 'dashboards#show', as: :dashboard
  # resources :restaurants, only: :update
  # resources :items, only: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :restaurant
  has_many :items, dependent: :destroy
  has_one_attached :photo
  validates :name, uniqueness: { scope: :restaurant, case_sensitive: false }
  validates :name, presence: true, length: { in: 2..15,
                                             too_long: "Category title length should be between 2 and 20 characters" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_restaurant!, only: :index
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(strong_params)
    @category.restaurant = current_restaurant
    if @category.save
      redirect_to restaurant_dashboard_path(current_restaurant)
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to restaurant_dashboard_path(current_restaurant)
    end
  end

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @categories = @restaurant.categories
  end

  private

  def strong_params
    params.require(:category).permit(:name, :photo)
  end
end

app/views/categories/index.html.erb
<%= render "shared/visitor-navbar" %>
<div class = "back-button">
  <%= link_to restaurant_path(@restaurant) do %>
    <i class="far fa-arrow-alt-circle-left arrow-left"></i>
  <% end %>
</div>
<div class="category-cards">
    <% @categories.each do |category| %>
      <%= link_to category_items_path(category), class: "category-card-link" do %>
        <div class="category-card">
          <div>
            <h1><%= category.name %></h1>
          </div>
          <% if category.photo.attached? %>
            <%= cl_image_tag category.photo.key %>
          <% end %>
        </div>
      <% end %>
    <% end %>
</div>